config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get "/sitemap.xml" => "welcome#sitemap", :defaults => {:format => :xml}

get "projects/:project_id/pages/:tab" => "project_tabs#show", :as => "project_tab"

resources :cms_menus
resources :cms_redirects

get 'page/:id/:version', :to => 'page#show', :constraints => {:version => /\d+/}
resources :pages do
  member do
   get :expire_cache
   get :history
   get :diff
   get :annotate
  end
end
resources :parts do
  member do
   get :expire_cache
   get :history
   get :diff
   get :annotate
  end
end
resources :pages_parts
resources :cms_variables

get "pages/:project_id/:id" => "pages#show"

post "pages/:page_id/add_part" => "pages_parts#add"
delete "pages/:page_id/delete_part/:part_id" => "pages_parts#delete"
put "pages/:page_id/update/:part_id" => "pages_parts#update"

get 'attachments/thumbnail/:id(/:size)/:filename', :controller => 'attachments', :action => 'thumbnail', :id => /\d+/, :filename => /.*/, :size => /\d+/

resources :cms_settings do 
  collection do 
    post 'save'
  end
end

app/models/part.rb
class Part < ActiveRecord::Base
  unloadable
  include Redmine::SafeAttributes
  
  has_and_belongs_to_many :pages, :uniq => true

  acts_as_attachable
  acts_as_versionable

  default_scope {order(:part_type)}

  liquid_methods :name, :attachments, :title

  after_commit :touch_pages

  validates_uniqueness_of :name
  validates_presence_of :name, :part_type, :content_type
  validates_format_of :name, :with => /\A(?!\d+$)[a-z0-9\-_]*\z/

 [:content, :header, :footer, :sidebar].each do |name, params|
    src = <<-END_SRC
    def is_#{name}_type?
      self.part_type.strip.downcase == "#{name.to_s}"
    end
    END_SRC
    class_eval src, __FILE__, __LINE__
  end

  attr_protected :id
  safe_attributes 'name',
    'part_type',
    'content_type',
    'is_cached',
    'content'
  
  def copy_from(arg)
    part = arg.is_a?(Part) ? arg : Part.find_by_id(arg)
    self.attributes = part.attributes.dup.except("id", "name", "created_at", "updated_at") if part
    self
  end

  def to_s
    "#{ERB::Util.html_escape(name)} (#{content_type})"
  end

private
  def touch_pages
    pages.each{|p| p.touch} if pages
  end

end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  unloadable
  before_filter :require_edit_permission
  before_filter :find_part, :except => [:index, :new, :create]

  helper :attachments
  helper :cms

  def index
    redirect_to :controller => 'pages', :action => 'index', :tab => "parts"
  end

  def show
    set_content_from_version if params[:version]
    redirect_to edit_part_path(@part) if %w(css java_script).include?(@part.content_type)
  end

  def edit
    set_content_from_version if params[:version]
  end

  def expire_cache
    Rails.cache.delete(@part)
    redirect_to :back
  end

  def new
    @part = Part.new(:content_type => 'textile')
    @part.copy_from(params[:copy_from]) if params[:copy_from]
  end

  def refresh
    expire_fragment(@part)
  end

  def update
    @part.assign_attributes(params[:part])
    @part.save_attachments(params[:attachments])
    if @part.save
      render_attachment_warning_if_needed(@part)
      flash[:notice] = l(:notice_successful_update)
      respond_to do |format|
        format.html do
          # if params[:unlock]
          #   redirect_to :controller => 'pages', :action => 'index', :tab => "parts"
          # else
            redirect_to :action =>"edit", :id => @part
          # end
        end
        format.js {render :nothing => true}
      end


    else
      render :action => 'edit'
    end
  end

  def create
    @part = Part.new(params[:part])
    @part.save_attachments(params[:attachments])
    if @part.save
      render_attachment_warning_if_needed(@part)
      flash[:notice] = l(:notice_successful_create)
      redirect_to :action =>"edit", :id => @part
    else
      render :action => 'new'
    end
  end

  def destroy
    if params[:version]
      version = @part.versions.where(:version => params[:version]).first
      if version.current_version?
        flash[:warning] = l(:label_cms_version_cannot_destroy_current)
      else
        version.destroy
      end
      redirect_to history_part_path(@page)
    else
      @part.destroy
      redirect_to :controller => 'pages', :action => 'index', :tab => "parts"
    end
  end

  def history
    @versions = @part.versions
    @version_count = @versions.count
  end

  def diff
    @diff = @part.diff(params[:version], params[:version_from])
    render_404 unless @diff
  end

  def annotate
    @annotate = @part.annotate(params[:version])
    render_404 unless @annotate
  end

private
  def find_part
    @part = Part.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def require_edit_permission
    deny_access unless RedmineCms.allow_edit?
  end

  def set_content_from_version
    return if !@page
    @version = @page.versions.where(:version => params[:version]).first
    @page.content = @version.content if @version
  end

end

app/helpers/parts_helper.rb
module PartsHelper
  def change_part_status_link(part)
    url = {:controller => 'parts', :action => 'update', :id => part, :part => params[:part], :status => params[:status], :tab => nil}

    if part.active?
      link_to l(:button_lock), url.merge(:part => {:status_id => RedmineCms::STATUS_LOCKED}, :unlock => true), :method => :put, :class => 'icon icon-lock'
    else
      link_to l(:button_unlock), url.merge(:part => {:status_id => RedmineCms::STATUS_ACTIVE}, :unlock => true), :method => :put, :class => 'icon icon-unlock'
    end
  end

  def parts_type_collection
    [["Pages", [["Content", "content"],
                ["Sections", "sections"],
                ["Sidebar", "sidebar"],
                ["Header", "header"],
                ["Footer", "footer"],
                ["Header tags", "header_tags"]]],
     ["Layout", [["Layout html head", "layout_html_head_part"],
                 ["Layout sidebar top", "layout_base_sidebar"],
                 ["Layout body top", "layout_body_top_part"],
                 ["Layout body bottom", "layout_body_bottom_part"]]]]
  end

  def parts_option_for_select
    parts = Part.order(:part_type).where("#{Part.table_name}.part_type NOT LIKE 'layout_%'").order(:content_type)
    return "" unless parts.any?
    previous_group = parts.first.part_type
    s = "<optgroup label=\"#{ERB::Util.html_escape(parts.first.part_type)}\">".html_safe
    parts.each do |part|
      if part.part_type != previous_group
        reset_cycle
        s << '</optgroup>'.html_safe
        s << "<optgroup label=\"#{ERB::Util.html_escape(part.part_type)}\">".html_safe
        previous_group = part.part_type
      end
      s << %Q(<option value="#{ERB::Util.html_escape(part.id)}">#{part.to_s}</option>).html_safe
    end
    s << '</optgroup>'.html_safe
    s.html_safe
  end
end

app/views/parts/_form.html.erb
<%= error_messages_for 'part' %>

<div class="box tabular">
<p><%= f.text_field :name, :size => 30, :required => true, :label => l(:label_cms_part_name)  %></p>
<p><%= f.select :part_type, grouped_options_for_select(parts_type_collection,  @part.part_type), :label => l(:label_cms_part_type) %></p>

<p><%= f.select :content_type, options_for_select([["Textile", "textile"], ["HTML", "html"]],  @part.content_type), :label => l(:label_cms_part_content_type) %></p>

<p><%= f.check_box :is_cached, :label => l(:label_cms_is_cached) %></p>

<p id="attachments_form"><label><%= l(:label_attachment_plural) %></label><%= render :partial => 'attachments/form', :locals => {:container => @part} %></p>

<%= text_area_tag 'part[content]', @part.content, :cols => 100, :rows =>  30, :class => 'wiki-edit' %>

<%= javascript_tag "editor = activateCodeMirror('part_content');" %>
<%= javascript_tag "$('.contextual.page-edit').draggable();" %>

</div>


<% content_for :header_tags do %>
  <%= code_mirror_tags %>
  <%= javascript_include_tag 'redmine_cms', :plugin => 'redmine_cms'  %>
<% end %>


<% content_for :header do %>
  <div class="contextual page-edit" id="float_buttons">
    <%= link_to l(:label_cms_apply), "#", :class => "icon icon-checked", :remote => true, :onclick => "editor.save(); $.ajax({url: '#{escape_javascript url_for(@part)}', type: \'post\', data: $(\'#part_form\').serialize()});return false;"%>
  </div>
<% end %>

app/views/parts/_parts.html.erb
<div class="contextual">
<%= link_to l(:label_cms_part_new), new_part_path, :class => 'icon icon-add' %>
</div>

<h3><%=l(:label_cms_part_plural)%></h3>

<div class="autoscroll">
<table class="list">
  <thead><tr>
    <th><%= l(:label_cms_part_name) %></th>
    <th><%= l(:label_cms_part_content) %></th>
    <th></th>
  </tr></thead>
  <% previous_group = false %>
  <tbody>
<% for part in @parts -%>
    <% if part.part_type != previous_group %>
      <% reset_cycle %>
      <tr class="group open">
        <td colspan="3">
          <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
          <%= part.part_type.blank? ? 'None' : part.part_type %> 
          <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}", "toggleAllRowGroups(this)", :class => 'toggle-all') %>
        </td>
      </tr>
      <% previous_group = part.part_type %>
    <% end %>


  <tr class="part <%= cycle("odd", "even") %> ">
  <td class="name"><%= link_to h(part.name), edit_part_path(part) %></td>
  <td class="type"><%= part.content_type %></td>
    <td class="buttons">
      <%= link_to l(:label_history), history_part_path(part), :class => 'icon icon-history' %>
      <%= link_to l(:button_duplicate), {:controller => 'parts', :action => 'new', :copy_from => part }, :class => 'icon icon-duplicate' %>
      <%= delete_link part_path(part, :back_url => parts_path) %>
    </td>
  </tr>
<% end -%>
  </tbody>
</table>
</div>

<% html_title(l(:label_cms_part_plural)) -%>

app/views/parts/annotate.html.erb
<div class="contextual">
  <%= link_to(l(:button_edit), {:action => 'edit', :id => @part}, :class => 'icon icon-edit') %>
  <%= link_to(l(:label_history),
              {:action => 'history', :id => @part}, :class => 'icon icon-history') %>
</div>


<%= cms_title [@part.name, part_path(@part, :version => nil)], l(:label_history) %>

<p>
  <em><%= @annotate.content.author ? link_to_user(@annotate.content.author) : l(:label_user_anonymous)
       %>, <%= format_time(@annotate.content.updated_at) %> </em><br />
  <%= @annotate.content.comments %>
</p>

<% colors = Hash.new {|k,v| k[v] = (k.size % 12) } %>

<table class="filecontent annotate">
  <tbody>
    <% line_num = 1 %>
    <% @annotate.lines.each do |line| -%>
      <tr class="bloc-<%= colors[line[0]] %>">
          <th class="line-num"><%= line_num %></th>
          <td class="revision"><%= link_to line[0], part_path(@part, :version => line[0] ) %></td>
          <td class="author"><%= line[1] %></td>
          <td class="line-code"><pre><%= line[2] %></pre></td>
      </tr>
    <% line_num += 1 %>
    <% end -%>
  </tbody>
</table>

<% content_for :header_tags do %>
<%= stylesheet_link_tag 'scm' %>
<% end %>

app/views/parts/diff.html.erb
<div class="contextual">
  <%= link_to l(:label_history), history_part_path(@part),
            :class => 'icon icon-history' %>
</div>

<%= cms_title [@part.name, part_path(@part, @part.name, :version => nil)],
      [l(:label_history), history_part_path(@part, @part.name)],
      "#{l(:label_version)} #{@diff.version_to.version}" %>

<p>
  <%= l(:label_version) %> <%= link_to @diff.version_from.version, :action => 'show', :id => @part, :version => @diff.version_from %>
  <em>(<%= @diff.version_from.author ?
               @diff.version_from.author.name : l(:label_user_anonymous)
        %>, <%= format_time(@diff.version_from.updated_at) %>)</em>
  &#8594;
  <%= l(:label_version) %> <%= link_to @diff.version_to.version, :action => 'show',
                               :id => @part,
                               :version => @diff.version_to.version
                            %>/<%= @part.version %>
  <em>(<%= @diff.version_to.author ?
               link_to_user(@diff.version_to.author.name) : l(:label_user_anonymous)
        %>, <%= format_time(@diff.version_to.updated_at) %>)</em>
</p>

<div class="text-diff">
  <%= simple_format_without_paragraph @diff.to_html %>
</div>

app/views/parts/edit.html.erb
<div class="contextual">
  <%= link_to l(:label_history), history_part_path(@part), :class => 'icon icon-history' %> 
  <%= link_to l(:button_duplicate), {:controller => 'parts', :action => 'new', :copy_from => @part }, :class => 'icon icon-duplicate' %>
  <%= link_to l(:button_delete), {:controller => 'parts', :action => 'destroy', :id => @part}, :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' %>
</div>

<h2><%= link_to l(:label_cms_part_plural), parts_path %> &#187; <%=l(:label_cms_part)%> <%= link_to link_to @part.name, part_url(@part)%></h2>

<%= labelled_form_for :part, @part, :url => { :action => 'update', :id => @part},
  :html => { :id => 'part_form', :multipart => true, :method => :put } do |f| %>

<%= render :partial => 'form', :locals => { :f => f } %>
<fieldset><legend><%= l(:label_attachment_plural) %></legend>
  <%= link_to_attachments @part, :thumbnails => true  %>
</fieldset><br/>

<%= submit_tag l(:button_save) %>
<%= link_to l(:label_cms_apply), "#", :style => "margin-left:10px;", :remote => true, :onclick => "editor.save(); $.ajax({url: '#{escape_javascript url_for(@part)}', type: \'post\', data: $(\'#part_form\').serialize()});return false;"%>
<% end %>

app/views/parts/history.html.erb
<%= cms_title [@part.name, edit_part_path(@part, :version => nil)], l(:label_history) %>

<%= form_tag({:controller => 'parts', :action => 'diff',
              :id => @part},
              :method => :get) do %>
  <table class="list wiki-page-versions">
    <thead>
      <tr>
        <th>#</th>
        <th></th>
        <th></th>
        <th><%= l(:field_updated_on) %></th>
        <th><%= l(:field_author) %></th>
        <th><%= l(:field_comments) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% show_diff = @versions.size > 1 %>
      <% line_num = 1 %>
      <% @versions.each do |ver| %>
        <tr class="wiki-page-version <%= cycle("odd", "even") %>">
            <td class="id"><%= link_to ver.version, :action => 'show', :id => @part.id, :version => ver.version %></td>
            <td class="checkbox"><%= radio_button_tag('version', ver.version, (line_num==1), :id => "cb-#{line_num}", :onclick => "$('#cbto-#{line_num+1}').prop('checked', true);") if show_diff && (line_num < @versions.size) %></td>
            <td class="checkbox"><%= radio_button_tag('version_from', ver.version, (line_num==2), :id => "cbto-#{line_num}") if show_diff && (line_num > 1) %></td>
            <td class="updated_on"><%= format_time(ver.updated_at) %></td>
            <td class="author"><%= link_to_user ver.author %></td>
            <td class="comments"><%= ver.comments %></td>
            <td class="buttons">
              <%= link_to l(:button_annotate), :action => 'annotate', :id => @part, :version => ver.version %>
              <%= delete_link page_path(@part, :version => ver.version) if @version_count > 1 %>
            </td>
        </tr>
        <% line_num += 1 %>
      <% end %>
    </tbody>
  </table>
  <%= submit_tag l(:label_view_diff), :class => 'small' if show_diff %>
<% end %>

app/views/parts/new.html.erb
<h2><%=l(:label_cms_part_new)%></h2>

<%= labelled_form_for :part, @part, :url => { :action => 'create', :project_id => @project },
  :html => { :id => 'part-form', :multipart => true }  do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_create) %>
<% end %>

app/views/parts/show.html.erb
<p><%= breadcrumb [link_to(l(:label_cms_part_plural), parts_path)] %></p>

<h2><%="#{l(:label_cms_part)}: #{@part.name}"%></h2>

<% if @part.is_header_type? %>
  <% content_for :header do %>
    <%= render_part @part %>
  <% end %>
<% elsif @part.is_sidebar_type? %>
  <% content_for :sidebar do  %>
    <%= render_part @part %>
  <% end %>
<% else %>
  <div class="wiki page part <%= @part.name %>">
    <%= render_part @part %>
  </div>
<% end %>

<% content_for :header do %>
  <div class="contextual page-edit">
    <%= link_to l(:button_edit), edit_part_path(@part), :class => 'icon icon-edit' %>
    <hr>
    <%= link_to l(:label_cms_refresh_cache), expire_cache_part_path(@part), :class => 'icon icon-reload' %>
  </div>
  <%= javascript_tag "$('.contextual.page-edit').draggable();" %>
<% end if RedmineCms.allow_edit? %>