config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get "/sitemap.xml" => "welcome#sitemap", :defaults => {:format => :xml}

get "projects/:project_id/pages/:tab" => "project_tabs#show", :as => "project_tab"

resources :cms_menus
resources :cms_redirects

get 'page/:id/:version', :to => 'page#show', :constraints => {:version => /\d+/}
resources :pages do
  member do
   get :expire_cache
   get :history
   get :diff
   get :annotate
  end
end
resources :parts do
  member do
   get :expire_cache
   get :history
   get :diff
   get :annotate
  end
end
resources :pages_parts
resources :cms_variables

get "pages/:project_id/:id" => "pages#show"

post "pages/:page_id/add_part" => "pages_parts#add"
delete "pages/:page_id/delete_part/:part_id" => "pages_parts#delete"
put "pages/:page_id/update/:part_id" => "pages_parts#update"

get 'attachments/thumbnail/:id(/:size)/:filename', :controller => 'attachments', :action => 'thumbnail', :id => /\d+/, :filename => /.*/, :size => /\d+/

resources :cms_settings do 
  collection do 
    post 'save'
  end
end

app/models/cms_menu.rb
class CmsMenu < ActiveRecord::Base
  unloadable
  include Redmine::SafeAttributes

  belongs_to :source, :polymorphic => true

  acts_as_list :scope => 'menu_type = \'#{menu_type}\' AND parent_id #{parent_id ? \'=\' + parent_id : \'IS NULL\'}'
  acts_as_tree :dependent => :nullify

  default_scope {order(:menu_type).order(:position)}
  scope :active, lambda {where(:status_id => RedmineCms::STATUS_ACTIVE)}
  scope :visible, lambda { where(CmsMenu.visible_condition) }
  scope :footer_menu, lambda { where(:menu_type => "footer_menu")}
  scope :top_menu, lambda{where(:menu_type => "top_menu")}
  scope :account_menu, lambda{where(:menu_type => "account_menu")}

  after_commit :rebuild_menu

  validates_presence_of :name, :caption
  validates_uniqueness_of :name, :scope => :menu_type
  validates_length_of :name, :maximum => 30
  validates_length_of :caption, :maximum => 255
  validate :validate_menu
  validates_format_of :name, :with => /\A(?!\d+$)[a-z0-9\-_]*\z/

  @cached_cleared_on = Time.now

  attr_protected :id
  safe_attributes 'name',
    'caption',
    'path',
    'position',
    'status_id',
    'visibility',
    'menu_type'

  def self.visible_condition(user=User.current)
    user_ids = [user.id] + user.groups.map(&:id)
    return "(1=1)" if user.admin?
    cond = ""
    cond << " ((#{table_name}.visibility = 'public')"
    cond << " OR (#{table_name}.visibility = 'logged')" if user.logged?
    cond << " OR (#{table_name}.visibility IN (#{user_ids.join(',')})))" if user.logged?
  end

  def visible?(user=User.current)
    return true if user.admin?
    return true if visibility == 'public'
    return true if visibility == 'logged' && user.logged?
    user_ids = [user.id] + user.groups.map(&:id)
    return true if user_ids.include?(visibility.to_i) && user.logged?
    false
  end

  def active?
    self.status_id == RedmineCms::STATUS_ACTIVE
  end

  def rebuild_menu
    CmsMenu.rebuild
  end

  def reload(*args)
    @valid_parents = nil
    super
  end

  def self.menu_tree(menus, parent_id=nil, level=0)
    tree = []
    menus.select {|menu| menu.parent_id == parent_id}.sort_by(&:position).sort_by(&:menu_type).each do |menu|
      tree << [menu, level]
      tree += menu_tree(menus, menu.id, level+1)
    end
    if block_given?
      tree.each do |menu, level|
        yield menu, level
      end
    end
    tree
  end

  def self.check_cache
    menu_updated_on = CmsMenu.maximum(:updated_at)
    if menu_updated_on && @cached_cleared_on <= menu_updated_on
      clear_cache
    end
  end

  # Clears the settings cache
  def self.clear_cache
    CmsMenu.rebuild
    @cached_cleared_on = Time.now
    logger.info "Menu cache cleared." if logger
  end

  def self.rebuild
    Redmine::MenuManager.map :top_menu do |menu|
      CmsMenu.top_menu.each{|m| menu.delete(m.name.to_sym) }

      CmsMenu.active.top_menu.where(:parent_id => nil).each do |cms_menu|
        menu.push(
          cms_menu.name, 
          cms_menu.path, 
          :caption => cms_menu.caption, 
          :first => cms_menu.first?, 
          :if => Proc.new{|p| cms_menu.visible? } 
        ) unless menu.exists?(cms_menu.name.to_sym)
      end

      CmsMenu.active.top_menu.where("#{CmsMenu.table_name}.parent_id IS NOT NULL").each do |cms_menu|
        menu.push(
          cms_menu.name.to_sym, 
          cms_menu.path, 
          :parent => cms_menu.parent.name.to_sym, 
          :caption => cms_menu.caption, :if => Proc.new{|p| cms_menu.visible? && cms_menu.parent.visible?  }
        ) if cms_menu.parent.active? && !menu.exists?(cms_menu.name.to_sym)

      end
    end

    Redmine::MenuManager.map :account_menu do |menu|
      CmsMenu.account_menu.each{|m| menu.delete(m.name.to_sym) }

      CmsMenu.active.account_menu.where(:parent_id => nil).each do |cms_menu|
        menu.push(
          cms_menu.name, 
          cms_menu.path, 
          :caption => cms_menu.caption, 
          :first => cms_menu.first? 
        ) unless menu.exists?(cms_menu.name.to_sym)
      end

      CmsMenu.active.account_menu.where("#{CmsMenu.table_name}.parent_id IS NOT NULL").each do |cms_menu|
        menu.push( 
          cms_menu.name.to_sym, 
          cms_menu.path, 
          :parent => cms_menu.parent.name.to_sym, 
          :caption => cms_menu.caption) if cms_menu.parent.active? && cms_menu.parent.visible? && !menu.exists?(cms_menu.name.to_sym)

      end
    end

    Redmine::MenuManager.map :footer_menu do |menu|
      CmsMenu.footer_menu.each{|m| menu.delete(m.name.to_sym) }
      CmsMenu.active.footer_menu.each do |cms_menu|
        menu.push(cms_menu.name, cms_menu.path, :caption => cms_menu.caption, :if => Proc.new{|p| cms_menu.visible? })
      end
    end

  end

  def valid_parents
    @valid_parents ||= (self.children.any? ? [] : CmsMenu.where(:menu_type => self.menu_type, :parent_id => nil) - self_and_descendants)
  end

  protected

  def validate_menu
    if parent_id && parent_id_changed?
      errors.add(:parent_id, :invalid) unless valid_parents.include?(parent)
    end
  end

end

app/controllers/cms_menus_controller.rb
class CmsMenusController < ApplicationController
  unloadable

  before_filter :require_edit_permission
  before_filter :find_menu, :except => [:index, :new, :create]

  helper :cms

  def index
    redirect_to :controller => 'pages', :action => 'index', :tab => "cms_menus"
  end

  def edit

  end

  def new
    @cms_menu = CmsMenu.new
  end

  def update
    @cms_menu.assign_attributes(params[:cms_menu])
    if @cms_menu.save
      flash[:notice] = l(:notice_successful_update)
      @cms_menus = CmsMenu.all
      respond_to do |format|
        format.html {render :action =>"edit", :id => @cms_menus}
        format.js {render :action => "change"}
      end
    else
      render :action => 'edit'
    end
  end

  def create
    @cms_menu = CmsMenu.new(params[:cms_menu])
    if @cms_menu.save
      flash[:notice] = l(:notice_successful_create)
      render :action => 'edit', :id => @cms_menu
    else
      render :action => 'new'
    end
  end

  def destroy
    @cms_menu.destroy
    redirect_to :controller => 'pages', :action => 'index', :tab => "cms_menus"
  end

private
 def find_menu
  @cms_menu = CmsMenu.find(params[:id])
 end


  def require_edit_permission
    deny_access unless RedmineCms.allow_edit?
  end

end

app/helpers/cms_menus_helper.rb
module CmsMenusHelper

  def change_menu_status_link(cms_menu)
    url = {:controller => 'cms_menus', :action => 'update', :id => cms_menu, :cms_menu => params[:cms_menu], :status => params[:status], :tab => nil}

    if cms_menu.active?
      link_to l(:button_lock), url.merge(:cms_menu => {:status_id => RedmineCms::STATUS_LOCKED}), :method => :put, :class => 'icon icon-lock'
    else
      link_to l(:button_unlock), url.merge(:cms_menu => {:status_id => RedmineCms::STATUS_ACTIVE}), :method => :put, :class => 'icon icon-unlock'
    end
  end

  def menus_options_for_select(menus)
    options = []
    CmsMenu.menu_tree(menus) do |menu, level|
      label = (level > 0 ? '&nbsp;' * 2 * level + '&#187; ' : '').html_safe
      label << menu.name
      options << [label, menu.id]
    end
    options    
  end

  def menu_tree(menus, &block)
    CmsMenu.menu_tree(menus, &block)
  end

end

app/views/cms_menus/_cms_menus.html.erb
<table class="list">
  <thead><tr>
    <th><%= l(:label_cms_menu_name) %></th>
    <th><%= l(:label_cms_menu_caption) %></th>
    <th></th>
    <th></th>
  </tr></thead>
  <% previous_group = false %>
  <tbody>

<% menu_tree(@cms_menus) do |menu, level| -%>
    <% if menu.menu_type != previous_group %>
      <% reset_cycle %>
      <tr class="group open">
        <td colspan="5">
          <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
          <%= menu.menu_type.blank? ? 'None' : menu.menu_type %>
          <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}", "toggleAllRowGroups(this)", :class => 'toggle-all') %>
        </td>
      </tr>
      <% previous_group = menu.menu_type %>
    <% end %>
  <tr class="menu project <%= cycle("odd", "even") %> <%= %w(disabled active)[menu.status_id] %> <%= level > 0 ? "idnt idnt-#{level}" : nil %>" id="cms_menu_<%= menu.id %>">
  <td class="name"><span><%= link_to menu.name, edit_cms_menu_path(menu), :title => menu.path %></span></td>
  <td class="name"><%= link_to menu.caption.html_safe, edit_cms_menu_path(menu), :title => menu.path %></td>
  <td><%= cms_reorder_links('cms_menu', {:controller => 'cms_menus', :action => 'update', :id => menu}, :put) %></td>
    <td class="buttons">
      <%= change_menu_status_link(menu) %>
      <%= delete_link cms_menu_path(menu, :back_url => cms_menus_path) %>
    </td>
  </tr>
<% end -%>
  </tbody>
</table>

app/views/cms_menus/_form.html.erb
<%= error_messages_for 'cms_menu' %>

<div class="box tabular attributes splitcontent">
  <div class="splitcontentleft">
    <p><%= f.text_field :name, :size => 30, :required => true, :label => l(:label_cms_menu_name)  %></p>
    <p><%= f.text_field :caption, :required => true, :label => l(:label_cms_menu_caption), :style => "width: 99%;" %></p>
    <p><%= f.text_field :path, :required => true, :label => l(:label_cms_menu_path) %></p>
    <p><%= f.text_field :position, :size => 5, :required => true, :label => l(:label_cms_position) %></p>
  </div>
  <div class="splitcontentright">
    <% if @cms_menu.valid_parents.any? %>
    <p><%= f.select :parent_id, menus_options_for_select(@cms_menu.valid_parents), :include_blank => true, :label => :label_cms_menu_parent %></p>
    <% end %>
    <p><%= f.select :status_id, options_for_select([["Disabled", 0], ["Active", 1]], @cms_menu.status_id), :label => l(:label_cms_menu_status)  %></p>

    <p><%= f.select :visibility, cms_visibilities_for_select(@cms_menu.visibility || "public"), :label => l(:label_cms_visibility)  %></p>

    <p><%= f.select :menu_type, options_for_select([["top_menu", "top_menu"], ["footer_menu", "footer_menu"], ["account_menu", "account_menu"]],  @cms_menu.menu_type), :label => l(:label_cms_menu_type) %></p>
  </div>
</div>

app/views/cms_menus/_index.html.erb
<div class="contextual">
<%= link_to l(:label_cms_menu_new), new_cms_menu_path, :class => 'icon icon-add' %>
</div>

<h3><%=l(:label_cms_menu_plural)%></h3>

<div class="autoscroll" id="cms_menus">
<%= render :partial => 'cms_menus/cms_menus' %>
</div>

<% html_title(l(:label_cms_menu_plural)) -%>

app/views/cms_menus/change.js.erb
$('#cms_menus').html('<%= escape_javascript(render :partial => 'cms_menus/cms_menus') %>');
$('#cms_menu_<%= @cms_menu.id %>').effect("highlight");

app/views/cms_menus/edit.html.erb
<h2><%= link_to l(:label_cms_menu_plural), cms_menus_path %> &#187; <%=l(:label_cms_menu)%> <%= @cms_menu.name %></h2>

<%= labelled_form_for :cms_menu, @cms_menu, :url => { :action => 'update', :id => @cms_menu},
  :html => { :id => 'cms_menu-form', :method => :put } do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_save) %>
<% end %>

app/views/cms_menus/new.html.erb
<h2><%=l(:label_cms_menu_new)%></h2>

<%= labelled_form_for :cms_menu, @cms_menu, :url => { :action => 'create', :id => @cms_menu},
  :html => { :id => 'cms_menu-form', :method => :post } do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_create) %>
<% end %>