config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get "/sitemap.xml" => "welcome#sitemap", :defaults => {:format => :xml}

get "projects/:project_id/pages/:tab" => "project_tabs#show", :as => "project_tab"

resources :cms_menus
resources :cms_redirects

get 'page/:id/:version', :to => 'page#show', :constraints => {:version => /\d+/}
resources :pages do
  member do
   get :expire_cache
   get :history
   get :diff
   get :annotate
  end
end
resources :parts do
  member do
   get :expire_cache
   get :history
   get :diff
   get :annotate
  end
end
resources :pages_parts
resources :cms_variables

get "pages/:project_id/:id" => "pages#show"

post "pages/:page_id/add_part" => "pages_parts#add"
delete "pages/:page_id/delete_part/:part_id" => "pages_parts#delete"
put "pages/:page_id/update/:part_id" => "pages_parts#update"

get 'attachments/thumbnail/:id(/:size)/:filename', :controller => 'attachments', :action => 'thumbnail', :id => /\d+/, :filename => /.*/, :size => /\d+/

resources :cms_settings do 
  collection do 
    post 'save'
  end
end

app/models/cms_variable.rb
class CmsVariable < ActiveRecord::Base
  unloadable
  include Redmine::SafeAttributes

  attr_protected :id
  safe_attributes 'name', 'value'

  validates_presence_of :name
  validates_format_of :name, :with => /\A(?!\d+$)[a-z0-9\-_]*\z/
  
end

app/controllers/cms_variables_controller.rb
class CmsVariablesController < ApplicationController

  before_filter :find_variable, :only => [:edit, :update, :destroy]
  before_filter :require_admin
  def new
    @variable = CmsVariable.new
  end

  def create
    @variable = CmsVariable.new
    @variable.safe_attributes = params[:cms_variable]
    if @variable.save
      flash[:notice] = l(:notice_successful_create)
      respond_to do |format|
        format.html { redirect_to cms_settings_path(:tab => "variables") }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :action => 'new' }
        format.js
      end
    end
  end

  def update
    @variable.safe_attributes = params[:cms_variable]
    if @variable.save
      flash[:notice] = l(:notice_successful_update)
      respond_to do |format|
        format.html { redirect_to cms_settings_path(:tab => "variables") }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :action => 'edit' }
        format.js
      end
    end
  end

  def edit
  end

  def destroy
    @variable.destroy
    respond_to do |format|
      format.html { redirect_to cms_settings_path(:tab => "variables") }
    end
  end

private
  
  def find_variable
    @variable = CmsVariable.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

end

app/views/cms_variables/_form.html.erb
<div class="box tabular">
  <%= error_messages_for f.object %>
  <p>
    cms_variable_<%= f.text_field :name, :required => true%>
  </p>
  <p>
    <%= f.text_field :value, :required => true%>
  </p>
</div>

app/views/cms_variables/_variables.html.erb
<div class="contextual">
<%= link_to l(:label_cms_variable_new), new_cms_variable_path, :class => 'icon icon-add' %>
</div>

<h3><%=l(:label_cms_variable_plural)%></h3>
<div class="autoscroll">
<table class="list">
  <thead><tr>
    <th><%= l(:label_cms_variable_name) %></th>
    <th><%= l(:label_cms_variable_value) %></th>
    <th></th>
  </tr></thead>
  <tbody>
<% CmsVariable.all.each do |var| -%>
  <tr class="page project <%= cycle("odd", "even") %>">
  <td class="name"><span style="color: #aaa;">cms_variable_</span><span><%= link_to h(var.name), edit_cms_variable_path(var) %></span></td>
  <td class="name"><%= var.value %></td>
    <td class="buttons">
      <%= delete_link cms_variable_path(var, :back_url => cms_variables_path) %>
    </td>
  </tr>
<% end -%>
  </tbody>
</table>
</div>

app/views/cms_variables/edit.html.erb
<h2><%=l(:label_cms_variable)%></h2>

<%= labelled_form_for @variable, :method => "PUT", :html => {:class => 'tabular'} do |f|%>
  <%= render :partial => 'form', :locals => { :f => f} %>
  <p>
    <%= f.submit l(:button_save) %>
  </p>
<% end %>

app/views/cms_variables/new.html.erb
<h2><%=l(:label_cms_variable_new)%></h2>

<%= labelled_form_for(@variable, :html => {:class => 'tabular'}) do |f|%>
  <%= render :partial => 'form', :locals => { :f => f} %>
  <p>
    <%= f.submit l(:button_create) %>
  </p>
<% end %>