config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get "/sitemap.xml" => "welcome#sitemap", :defaults => {:format => :xml}

get "projects/:project_id/pages/:tab" => "project_tabs#show", :as => "project_tab"

resources :cms_menus
resources :cms_redirects

get 'page/:id/:version', :to => 'page#show', :constraints => {:version => /\d+/}
resources :pages do
  member do
   get :expire_cache
   get :history
   get :diff
   get :annotate
  end
end
resources :parts do
  member do
   get :expire_cache
   get :history
   get :diff
   get :annotate
  end
end
resources :pages_parts
resources :cms_variables

get "pages/:project_id/:id" => "pages#show"

post "pages/:page_id/add_part" => "pages_parts#add"
delete "pages/:page_id/delete_part/:part_id" => "pages_parts#delete"
put "pages/:page_id/update/:part_id" => "pages_parts#update"

get 'attachments/thumbnail/:id(/:size)/:filename', :controller => 'attachments', :action => 'thumbnail', :id => /\d+/, :filename => /.*/, :size => /\d+/

resources :cms_settings do 
  collection do 
    post 'save'
  end
end

app/models/cms_redirect.rb
class CmsRedirect
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  include Redmine::SafeAttributes

  attr_accessor :source_path, :destination_path

  validates_presence_of :source_path, :destination_path
  validates_format_of :source_path, :with => /\A(?!\d+$)\/[a-z0-9\-_\/]*\z/i, :message => "Invalide format"
  validates_length_of :source_path, :destination_path, :maximum => 200
  validate :validate_redirect

  def self.all
    RedmineCms.redirects.map{|k, v| CmsRedirect.new(:source_path => k, :destination_path => v) }
  end

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def save
    if !valid?
      errors.messages.each{|k, msg| Rails.logger.info "attribute #{k} #{msg.first}('#{send(k)}')"}
      return false
    end
    redirects = Setting.plugin_redmine_cms["redirects"].is_a?(Hash) ? Setting.plugin_redmine_cms["redirects"] : {}
    redirects.merge!(source_path => destination_path)
    Setting.plugin_redmine_cms = Setting.plugin_redmine_cms.merge({"redirects" => redirects})
  end

  def destroy
    redirects = Setting.plugin_redmine_cms["redirects"].is_a?(Hash) ? Setting.plugin_redmine_cms["redirects"] : {}
    redirects.delete(source_path)
    Setting.plugin_redmine_cms = Setting.plugin_redmine_cms.merge({"redirects" => redirects})
    true
  end

  def to_param
    if source_path == "/"
      "_"
    else
      source_path.parameterize
    end
  end

  def persisted?
    false
  end

  private

  def validate_redirect

    if source_path.to_s.start_with?("/admin", "/settings", "/users", "/groups", "/plugins", "/cms_redirects")
      errors.add :source_path, 'Invalid source path'
    end
  end

end

app/controllers/cms_redirects_controller.rb
class CmsRedirectsController < ApplicationController
  unloadable

  before_filter :require_admin
  before_filter :find_redirect, :except => [:index, :new, :create]

  def index
    redirect_to :controller => 'cms_settings', :action => 'index', :tab => "cms_redirects"
  end

  def new
    @cms_redirect = CmsRedirect.new
  end

  def edit
  end

  def update
    new_cms_redirect = CmsRedirect.new(params[:cms_redirect])
    if new_cms_redirect.save
      @cms_redirect.destroy
      flash[:notice] = l(:notice_successful_update)
      redirect_to cms_redirects_path
    else
      source_path = @cms_redirect.source_path
      @cms_redirect = new_cms_redirect
      @cms_redirect.source_path = source_path
      render :action => 'edit'
    end
  end

  def create
    @cms_redirect = CmsRedirect.new(params[:cms_redirect])
    if @cms_redirect.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to cms_redirects_path
    else
      render :action => 'new'
    end
  end

  def destroy
    @cms_redirect.destroy
    redirect_to cms_redirects_path
  end

  private

  def find_redirect
    parametrized_redirects = RedmineCms.redirects.map{|k, v| [k, v]}.inject({}){|memo, (key, value)| memo[key.parameterize] = {:s => key, :d => value}; memo}
    redirect = parametrized_redirects[params[:id].gsub(/^_$/, "")]
    render_404 unless redirect
    @cms_redirect = CmsRedirect.new(:source_path => redirect.try(:[], :s), :destination_path => redirect.try(:[], :d))
  end
end

app/helpers/cms_redirects_helper.rb
module CmsRedirectsHelper
end

app/views/cms_redirects/_form.html.erb
<%= error_messages_for 'cms_redirect' %>

<div class="box tabular">
<p><%= f.text_field :source_path, :size => 100, :required => true, :label => l(:label_cms_source_path)  %></p>
<p><%= f.text_field :destination_path, :size => 100, :required => true, :label => l(:label_cms_destination_path)  %></p>
</div>

app/views/cms_redirects/_index.html.erb
<div class="contextual">
<%= link_to l(:label_cms_redirect_new), new_cms_redirect_path, :class => 'icon icon-add' %>
</div>

<h3><%=l(:label_cms_redirect_plural)%></h3>

<div class="autoscroll">
<table class="list">
  <thead><tr>
    <th><%= l(:label_cms_source_path) %></th>
    <th><%= l(:label_cms_destination_path) %></th>
    <th></th>
  </tr></thead>
  <tbody>
<% @cms_redirects.each do |cms_redirect| -%>
  <tr class="cms_redirect project <%= cycle("odd", "even") %>">
    <td class="name"><%= link_to cms_redirect.source_path, edit_cms_redirect_path(cms_redirect) %></td>
    <td class="name"><%= cms_redirect.destination_path %></td>
    <td class="buttons">
      <%= delete_link cms_redirect_path(cms_redirect, :back_url => cms_redirects_path(params)) %>
    </td>
  </tr>
<% end -%>
  </tbody>
</table>
</div>

app/views/cms_redirects/edit.html.erb
<h2><%= link_to l(:label_cms_redirect_plural), cms_redirects_path %> &#187; <%=l(:label_cms_redirect)%></h2>

<%= labelled_form_for :cms_redirect, @cms_redirect, :url => { :action => 'update', :id => @cms_redirect},
  :html => { :id => 'cms_redirect-form', :method => :put } do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_save) %>
<% end %>

app/views/cms_redirects/new.html.erb
<h2><%=l(:label_cms_redirect_new)%></h2>

<%= labelled_form_for :cms_redirect, @cms_redirect, :url => { :action => 'create'},
  :html => { :id => 'cms_redirect-form', :method => :post } do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_create) %>
<% end %>